version: '3.3'
services:
  jenkins:
    build:
      context: ./
      dockerfile: ./Dockerfile-jenkins
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /jenkins_data_new1:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
